[package]
name = "sign"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "*"
home="*"
shellexpand="*"
solana-sdk="1.9.1"
serde_json="*"