name = "strangemood"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2021-12-29"

kv_namespaces = [ 
  { binding = "LISTINGS", id = "b6d2ca1116f94644832ff2c642d1ca68", preview_id="4c982034f48341e1b0852b384283a946" },
  { binding = "SIGNATURES", id="3e05cb55c2394f92a353939a0693506a", preview_id="aef87525301d420b9a915de94193a123" }
]

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
